### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by kghalamb**
Added some tests, but they don't work due to some unidentified jest errors.

### CODE REVIEW

**Comment by kghalamb** [comment]
I also found a typo in module-services.js where the user list was typed as "member_list" which I fixed, but someone should review that change in case it was not actually a typo after all.

**Comment by dayodin** [comment]
Looks like a good starting template for testing. Will be nice to have the files and baseline code going forward.

**Comment by kpmcnulty** [comment]
Looks good, we will need to add more cases later, but that will be easy with this already implemented

**Comment by ayang101** [comment]
Good progress so far on testing!
A note on your tests: the error seems to be when your comparing equality, you don't seem to be adding any objects into the collection, so that's why you get an undefined value when you try to extract an attribute from an object. The colllection is empty, so trying to find something in that collection results in undefined, leading to the error.

To fix this issue, you can either add a new object into the database from the cloud and/or application (when running both the frontend and the backend), or add it within your testing suite, just remember to clear the database after you compare.

**Comment by KGHALAMB** [comment]
> 

@ayang101 thanks for the note! I won't merge yet so I can try to fix the issue.

**Comment by kghalamb** [comment]
I am going to do a merge and try to apply @ayang101 's edits later.  I think it is good to have some foundations when it comes to testing for future use.

**Pull request merged**
